general:
  buildTool: "npm"

stages:

  Additional Unit Tests:

    npmExecuteScripts:
      runScripts:
        - test:opa      # OPA5 (Karma)
        - test:wdi5     # wdi5 tests
        - test:uiveri5  # UIVeri5 tests

    testsPublishResults:
      failOnError: false
      junit:
        pattern: "**/reports/TESTS.xml"
        archive: true
      cobertura:
        pattern: "**/coverage/coverage.xml"
        archive: true

  Static Code Checks:

    sonarExecuteScan:
      serverUrl: "https://sonar-dev.releaseowl.com"
      projectKey: "execute-test-cases"
      waitForQualityGate: true