general:
  buildTool: "npm"
  verbose: true

stages:

  Additional Unit Tests:

    wdi5Tests:
      type: npmExecuteTests
      params:
        script: this
        dockerImage: "devxci/mbtci-java17-node20"
        dockerSidecarImage: "selenium/standalone-chrome"
        runAsRoot: true
        installCommand: "npm install"
        runCommand: "npm run wdi5:ci"
        baseUrl: "http://node:8080"
        urlOptionPrefix: "--base-url="
        envs:
          - "NPM_CONFIG_PREFIX=~/.npm-global"
        paths:
          - "~/.npm-global/bin"
        verbose: true

    uiveri5Tests:
      type: npmExecuteTests
      params:
        script: this
        dockerImage: "devxci/mbtci-java17-node20"
        dockerSidecarImage: "selenium/standalone-chrome"
        runAsRoot: true
        installCommand: "npm install -g @ui5/uiveri5"
        runCommand: "uiveri5"
        baseUrl: "http://node:8080"
        urlOptionPrefix: "--base-url="
        runOptions:
          - "--seleniumAddress=http://selenium:4444/wd/hub"
        envs:
          - "NPM_CONFIG_PREFIX=~/.npm-global"
        paths:
          - "~/.npm-global/bin"
        verbose: true

    testsPublishResults:
      failOnError: false
      junit:
        pattern: "**/reports/TESTS*.xml"
        archive: true

  Static Code Checks:

    sonarExecuteScan:
      serverUrl: "https://sonar-dev.releaseowl.com"
      projectKey: "execute-test-cases"
      waitForQualityGate: true